workflows:
  ios-build:
    name: iOS Build (Flutter)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - "build/ios/ipa/*.ipa"
      - "build/ios/archive/*.xcarchive"
      - "**/build/**/*.app"
      - "**/build/**/*.ipa"
    publishing:
      email:
        recipients:
          - tu_correo@ejemplo.com
