workflows:
  ios-build:
    name: iOS Build (Flutter)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

    scripts:
      # 1️⃣ Obtener dependencias
      - name: Flutter pub get
        script: flutter pub get

      # 2️⃣ Compilar para iOS
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - **/build/**/*.app

    publishing:
      email:
        recipients:
          - "sriverasc12@gmail.com"
