workflows:
  ios-build:
    name: iOS Build (Flutter - Simulator)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          flutter pub get

      - name: Build iOS Simulator app
        script: |
          flutter build ios --simulator --debug

      - name: Zip Runner.app for Appetize
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - build/ios/iphonesimulator/Runner.app.zip

    publishing:
      email:
        recipients:
          - sriverasc12@gmail.com
